/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodTruckPermitsCityRouteImport } from './routes/food-truck-permits.$city'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppPermitsNewRouteImport } from './routes/_authenticated.app.permits.new'
import { Route as AuthenticatedAppPermitsIdRouteImport } from './routes/_authenticated.app.permits.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodTruckPermitsCityRoute = FoodTruckPermitsCityRouteImport.update({
  id: '/food-truck-permits/$city',
  path: '/food-truck-permits/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPermitsNewRoute =
  AuthenticatedAppPermitsNewRouteImport.update({
    id: '/permits/new',
    path: '/permits/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPermitsIdRoute =
  AuthenticatedAppPermitsIdRouteImport.update({
    id: '/permits/$id',
    path: '/permits/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/food-truck-permits/$city': typeof FoodTruckPermitsCityRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/permits/$id': typeof AuthenticatedAppPermitsIdRoute
  '/app/permits/new': typeof AuthenticatedAppPermitsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/food-truck-permits/$city': typeof FoodTruckPermitsCityRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/permits/$id': typeof AuthenticatedAppPermitsIdRoute
  '/app/permits/new': typeof AuthenticatedAppPermitsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/food-truck-permits/$city': typeof FoodTruckPermitsCityRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/permits/$id': typeof AuthenticatedAppPermitsIdRoute
  '/_authenticated/app/permits/new': typeof AuthenticatedAppPermitsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app'
    | '/food-truck-permits/$city'
    | '/app/'
    | '/app/permits/$id'
    | '/app/permits/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/food-truck-permits/$city'
    | '/app'
    | '/app/permits/$id'
    | '/app/permits/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/food-truck-permits/$city'
    | '/_authenticated/app/'
    | '/_authenticated/app/permits/$id'
    | '/_authenticated/app/permits/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FoodTruckPermitsCityRoute: typeof FoodTruckPermitsCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-truck-permits/$city': {
      id: '/food-truck-permits/$city'
      path: '/food-truck-permits/$city'
      fullPath: '/food-truck-permits/$city'
      preLoaderRoute: typeof FoodTruckPermitsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/permits/new': {
      id: '/_authenticated/app/permits/new'
      path: '/permits/new'
      fullPath: '/app/permits/new'
      preLoaderRoute: typeof AuthenticatedAppPermitsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/permits/$id': {
      id: '/_authenticated/app/permits/$id'
      path: '/permits/$id'
      fullPath: '/app/permits/$id'
      preLoaderRoute: typeof AuthenticatedAppPermitsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPermitsIdRoute: typeof AuthenticatedAppPermitsIdRoute
  AuthenticatedAppPermitsNewRoute: typeof AuthenticatedAppPermitsNewRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPermitsIdRoute: AuthenticatedAppPermitsIdRoute,
  AuthenticatedAppPermitsNewRoute: AuthenticatedAppPermitsNewRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FoodTruckPermitsCityRoute: FoodTruckPermitsCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
